/* groovylint-disable-next-line CompileStatic */
pipeline {
    agent any
    environment {
        TRAIN_PATH      = 'train/train.csv'
        TRAIN_PREP_PATH = 'train/train_prep.csv'
        TEST_PATH       = 'test/test.csv'
        TEST_PREP_PATH  = 'test/test_prep.csv'
        MODEL_PATH      = 'model/model.pkl'
    }
    stages {
        stage('Data creation') {
            steps {
                echo 'Data creation (start)'
                sh 'python3 MLOps/Lab-2/src/data_creation.py'
                echo 'Data creation (end)'
            }
        }
        stage('Data preprocessing') {
            steps {
                echo 'Data preprocessing (start)'
                sh 'python3 MLOps/Lab-2/src/data_preprocessing.py'
                echo 'Data preprocessing (end)'
            }
        }
        stage('Model preparation') {
            steps {
                echo 'Model preparation (start)'
                sh 'python3 MLOps/Lab-2/src/model_preparation.py'
                echo 'Model preparation (end)'
            }
        }
        stage('Model testing') {
            steps {
                echo 'Model testing (start)'
                sh 'python3 MLOps/Lab-2/src/model_testing.py'
                echo 'Model testing (end)'
            }
        }
    }
}
