pipeline {
    agent any
    environment {
        TRAIN_PATH      = 'train/train.csv'
        TRAIN_PREP_PATH = 'train/train_prep.csv'
        TEST_PATH       = 'test/test.csv'
        TEST_PREP_PATH  = 'test/test_prep.csv'
        MODEL_PATH      = 'model/model.pkl'
        PROJECT_PATH    = 'MLOps/Lab-2'
    }
    stages {
        stage('Setup Python Environment') {
            steps {
                echo 'Setting up Python virtual environment'
                sh '''
                python3 -m venv venv
                . venv/bin/activate
                pip install -r $PROJECT_PATH/requirements.txt
                '''
            }
        }
        stage('Create Data') {
            steps {
                echo 'Data creation'
                sh '''
                . venv/bin/activate
                python3 $PROJECT_PATH/src/data_creation.py
                '''
            }
        }
        stage('Preprocess Data') {
            steps {
                echo 'Data preprocessing'
                sh '''
                . venv/bin/activate
                python3 $PROJECT_PATH/src/data_preprocessing.py
                '''
            }
        }
        stage('Prepare Model') {
            steps {
                echo 'Model preparation'
                sh '''
                . venv/bin/activate
                python3 $PROJECT_PATH/src/model_preparation.py
                '''
            }
        }
        stage('Test Model') {
            steps {
                echo 'Model testing'
                sh '''
                . venv/bin/activate
                python3 $PROJECT_PATH/src/model_testing.py
                '''
            }
        }
    }
}
